import { getLocales } from 'expo-localization';

// 语言判定跟随设备系统语言：zh 走中文，其余一律英文
let lang = 'zh';
try {
  const code = getLocales()[0]?.languageCode;
  if (code && code !== 'zh') lang = 'en';
} catch {}

const zh = {
  app_name: '放哪了',

  // 通用
  cancel: '取消',
  save: '保存',
  edit: '修改',
  rename: '重命名',
  delete: '删除',
  create_failed: '创建失败',
  rename_failed: '重命名失败',
  delete_failed: '删除失败',
  save_failed: '保存失败',
  need_permission: '需要权限',
  try_later: '请稍后再试',
  record_method: '记录方式',
  take_photo: '拍照',
  record_video: '录像',
  from_library: '从相册选',
  open_link_failed: '无法打开链接',

  // App.js
  tab_spaces: '我的家',
  tab_assistant: '助手',
  a11y_account: '账户和购买',

  // LoginScreen
  login_subtitle: 'AI 收纳师 · 拍照记录，随时找到',
  login_failed: '登录失败',
  login_dev: '开发模式登录',
  login_terms: '登录即表示同意用户协议和隐私政策',

  // AssistantScreen
  typing: '思考中',
  hero_title: '找东西，问我就行',
  hero_sub: '拍张照片记录，或直接问位置',
  hint_1: '护照在哪',
  hint_2: '充电线放哪了',
  hint_3: '剪刀呢',
  new_conv: '新对话',
  copied: '已复制',
  copy_failed: '复制失败',
  saved: '已保存',
  draft_more_shoot: '继续拍',
  draft_album: '相册',
  input_placeholder_media: '添加说明...',
  input_placeholder: '帮我找...',
  max_media: '最多可添加 {count} 个媒体',
  max_media_added: '已添加前 {count} 个媒体',
  error_prefix: '出错了: {message}',

  // AgentWorkflow
  tool_list_spaces: '查看空间',
  tool_list_positions: '查看位置',
  tool_get_position_items: '查看物品',
  tool_view_photo: '查看照片',
  tool_view_position_photo: '查看位置照片',
  tool_search_items: '搜索物品',
  tool_save_items: '整理数据',
  tool_update_item: '修改物品',
  tool_update_position: '修正位置',
  tool_delete_item: '删除物品',
  tool_submit_feedback: '记录反馈',
  wf_list_positions_of: '查看{name}的位置',
  wf_search_for: '搜索"{query}"',
  wf_no_records: '还没有记录',
  wf_no_positions: '暂无位置',
  wf_items_count: '{count} 件物品',
  wf_found_count: '找到 {count} 条记录',
  wf_viewed: '已查看',
  wf_draft_ready: '已整理成记录草稿',
  wf_updated: '已修改',
  wf_renamed_to: '已改为"{name}"',
  wf_fixed: '已修正',
  wf_deleted: '已删除',
  wf_feedback_logged: '已记录，会转给开发团队',

  // SuggestionCard
  sc_status_new: '新',
  sc_status_existing: '有',
  sc_status_missing: '?',
  sc_new_location: '新位置',
  sc_space_ph: '空间',
  sc_position_ph: '位置',
  sc_item_name_ph: '物品名称',
  sc_add_item: '添加物品',
  sc_count: '{count} 件',

  // SpacesScreen
  sp_title: '拍照记录，想找就问',
  sp_stat_spaces: '空间',
  sp_stat_positions: '位置',
  sp_stat_items: '物品',
  sp_capture: '记录物品',
  sp_add_space_ph: '空间名称，如 客厅、卧室',
  sp_my_spaces: '我的空间',
  sp_start: '开始记录',
  sp_count_suffix: '{count} 个',
  sp_item_count: '{count} 件物品',
  sp_no_positions: '暂无位置',
  sp_first_title: '拍一张，自动帮你整理',
  sp_first_text: 'AI 认出照片里的物品，空间和位置自动建好',
  sp_first_btn: '拍照记录',
  sp_manual_add: '手动添加空间',
  sp_rename_space: '重命名空间',
  sp_delete_space: '删除空间',
  sp_delete_space_msg: '确定删除"{name}"及其所有位置和物品？',
  web_prompt_action: '{name}\n输入 "delete" 删除，或输入新名称重命名，取消则留空：',
  web_confirm_delete: '确定删除"{name}"？',
  web_logout_confirm: '确定退出登录吗？数据仍会保留在你的账号中。',
  web_delete_account_confirm: '确定删除账号和已保存的数据吗？此操作无法撤销。',

  // SpaceDetailScreen
  sd_no_items: '暂无物品',
  sd_items_count: '{count}件物品',
  sd_items_with_first: '{first}等{count}件物品',
  sd_meta: '{positions} 个位置 · {items} 件物品',
  sd_empty_title: '还没有位置',
  sd_empty_text: '添加位置或拍照让 AI 自动识别',
  sd_add_pos_ph: '位置名称，如 书桌、衣柜第二层',
  sd_add_pos: '添加位置',
  sd_shoot_room: '拍这个房间',
  sd_rename_pos: '重命名位置',
  sd_rename_item: '重命名物品',

  // PaywallScreen
  pw_page_title: '我的',
  pw_plan_standard: '标准版',
  pw_plan_large: '大户型版',
  pw_plan_welcome: '新人会员',
  pw_plan_annual: '年卡',
  pw_price_standard: '¥68/年',
  pw_price_large: '¥128/年',
  pw_desc_standard: '一年会员，适合多数家庭；可持续拍照或录像识别、保存物品位置，并用文字查找。',
  pw_desc_large: '一年会员，适合多房间或物品更多的家庭；包含更多媒体识别额度和完整查找功能。',
  pw_cta: '开通',
  pw_current_plan: '当前版本',
  pw_plan_free: '免费版',
  pw_plan_expired: '会员已过期',
  pw_expires: '{date}到期',
  pw_one_year_later: '一年后',
  pw_expired_on: '已于 {date} 到期',
  pw_expired_generic: '会员有效期已结束',
  pw_meta_free: 'v{version} · 可开通年卡',
  pw_collapse: '收起方案',
  pw_upgrade: '升级方案',
  pw_subscribe: '开通会员',
  pw_restore: '恢复购买',
  pw_badge_recommend: '推荐',
  pw_auto_renew: '自动续订，可在 Apple ID 订阅管理中取消。',
  pw_privacy: '隐私政策',
  pw_terms: '用户协议',
  pw_store_unavailable: '商店商品暂时不可用',
  pw_store_not_ready: '商店商品还未准备好',
  pw_store_query_failed: '商店商品查询失败',
  pw_store_connect_timeout: '连接 App Store 超时',
  pw_store_read_timeout: '读取 App Store 商品超时',
  pw_iap_missing: '当前版本未包含内购模块',
  pw_purchase_pending_title: '购买待批准',
  pw_purchase_pending_msg: 'App Store 已收到请求，等待批准后会自动生效。',
  pw_purchase_failed: '购买失败',
  pw_purchase_failed_msg: 'App Store 暂时无法完成购买，请稍后再试。',
  pw_receipt_missing_title: '缺少购买凭证',
  pw_receipt_missing_msg: 'App Store 没有返回 receipt，请点"恢复购买"重试；如果仍失败，需要安装最新 TestFlight 构建再测。',
  pw_restored: '购买已恢复',
  pw_activated: '开通成功',
  pw_valid_until: '会员有效期至 {date}',
  pw_activated_msg: '一年会员权益已开通',
  pw_verify_failed: '验证失败',
  pw_purchase_unconfirmed_title: '购买待确认',
  pw_purchase_unconfirmed_msg: 'App Store 已完成支付，但购买凭证还没同步。请点"恢复购买"刷新会员状态。',
  pw_product_not_ready_title: '商品未就绪',
  pw_product_not_ready_msg: 'App Store 暂时没有返回 {id}，请稍后再试。',
  pw_product_loading_title: '商品还在加载',
  pw_processing: '处理中',
  pw_wait: '请稍候',
  pw_retry_later: '稍后重试',
  pw_dev_no_restore: '开发模式无需恢复购买',
  pw_nothing_restore: '无可恢复的购买',
  pw_restore_failed: '恢复失败',

  // 福利（付费页 + 新人页共用）
  bf_section: '新人福利',
  bf_section_meta: '领取会员、邀请码奖励都在这里',
  bf_claimed_title: '新人会员已领取',
  bf_claim_title: '领取新人会员',
  bf_claimed_meta: '会员权益已到账',
  bf_claim_meta: '可领取 {days} 天新人会员',
  bf_claimed: '已领取',
  bf_claiming: '领取中',
  bf_claim: '领取',
  bf_my_code: '我的邀请码',
  bf_redeemed_title: '邀请码已兑换',
  bf_enter_code: '填写邀请码',
  bf_redeemed_meta: '每个账号只能兑换一次',
  bf_redeem_meta: '兑换后双方各得额外奖励',
  bf_redeemed_ph: '已完成兑换',
  bf_code_ph: '输入邀请码',
  bf_redeemed_short: '已兑',
  bf_redeeming: '兑换中',
  bf_redeem: '兑换',
  bf_already_claimed: '你已经领取过新人会员',
  bf_claim_ok: '已领取 {days} 天新人会员',
  bf_claim_failed: '领取失败',
  bf_redeem_ok: '兑换成功，邀请奖励已到账',
  bf_redeem_failed: '兑换失败',
  bf_code_copied: '邀请码已复制',
  bf_share_text: '我的放哪了邀请码：{code}，填写后我们各得额外奖励',

  // 账号
  ac_section: '账号与数据',
  ac_section_meta: '可以退出登录，或删除账号和已保存的个人数据。',
  ac_logout: '退出登录',
  ac_delete: '删除账号',
  ac_logout_failed: '退出失败',
  ac_logout_msg: '退出后需要重新登录才能查看你的记录，数据不会被删除。',
  ac_delete_title: '删除账号和数据',
  ac_delete_msg: '删除后，你的账号、照片/视频记录、空间、位置、物品和对话内容将从服务中移除。此操作无法撤销。',
  ac_confirm_delete: '确认删除',

  // WelcomeBenefitScreen
  wb_nav: '新人福利',
  wb_title: '领取新人会员',
  wb_sub: '先拿会员体验，再填写邀请码拿额外奖励。',
  wb_claimed_meta: '会员权益已到账。',
  wb_gift: '送你 {days} 天新人会员',
  wb_redeemed_meta: '每个账号只能兑换一次。',
  wb_done: '进入放哪了',

  // OnboardingGuide
  og_title: '随手拍一张，开启收纳',
  og_text: '打开一个抽屉或柜子，拍张照。AI 会认出里面的物品并记住位置，以后找东西，问一句就行。',
  og_try: '拍一张试试',
  og_later: '稍后再说',

  // ui.js
  empty_default: '暂无内容'
};

const en = {
  app_name: 'FindIt',

  cancel: 'Cancel',
  save: 'Save',
  edit: 'Edit',
  rename: 'Rename',
  delete: 'Delete',
  create_failed: 'Create failed',
  rename_failed: 'Rename failed',
  delete_failed: 'Delete failed',
  save_failed: 'Save failed',
  need_permission: 'Permission needed',
  try_later: 'Please try again later',
  record_method: 'Add a record',
  take_photo: 'Take photo',
  record_video: 'Record video',
  from_library: 'Choose from library',
  open_link_failed: "Couldn't open link",

  tab_spaces: 'Home',
  tab_assistant: 'Assistant',
  a11y_account: 'Account & purchases',

  login_subtitle: 'AI home organizer · Snap it, find it anytime',
  login_failed: 'Sign-in failed',
  login_dev: 'Dev mode sign in',
  login_terms: 'By signing in you agree to the Terms of Service and Privacy Policy',

  typing: 'Thinking',
  hero_title: 'Looking for something? Just ask',
  hero_sub: 'Snap a photo to log items, or ask where things are',
  hint_1: 'Where is my passport',
  hint_2: 'Where did I put the charger',
  hint_3: 'Where are the scissors',
  new_conv: 'New chat',
  copied: 'Copied',
  copy_failed: 'Copy failed',
  saved: 'Saved',
  draft_more_shoot: 'Camera',
  draft_album: 'Library',
  input_placeholder_media: 'Add a note...',
  input_placeholder: 'Find something...',
  max_media: 'You can add up to {count} files',
  max_media_added: 'Added the first {count} files',
  error_prefix: 'Something went wrong: {message}',

  tool_list_spaces: 'Viewing rooms',
  tool_list_positions: 'Viewing spots',
  tool_get_position_items: 'Viewing items',
  tool_view_photo: 'Viewing photo',
  tool_view_position_photo: 'Viewing spot photo',
  tool_search_items: 'Searching items',
  tool_save_items: 'Organizing',
  tool_update_item: 'Updating item',
  tool_update_position: 'Updating spot',
  tool_delete_item: 'Deleting item',
  tool_submit_feedback: 'Logging feedback',
  wf_list_positions_of: 'Spots in {name}',
  wf_search_for: 'Searching "{query}"',
  wf_no_records: 'No records yet',
  wf_no_positions: 'No spots yet',
  wf_items_count: '{count} items',
  wf_found_count: 'Found {count} records',
  wf_viewed: 'Viewed',
  wf_draft_ready: 'Draft ready to save',
  wf_updated: 'Updated',
  wf_renamed_to: 'Renamed to "{name}"',
  wf_fixed: 'Updated',
  wf_deleted: 'Deleted',
  wf_feedback_logged: "Logged — we'll pass it to the team",

  sc_status_new: 'N',
  sc_status_existing: '✓',
  sc_status_missing: '?',
  sc_new_location: 'New spot',
  sc_space_ph: 'Room',
  sc_position_ph: 'Spot',
  sc_item_name_ph: 'Item name',
  sc_add_item: 'Add item',
  sc_count: '{count} items',

  sp_title: 'Snap it, then just ask',
  sp_stat_spaces: 'Rooms',
  sp_stat_positions: 'Spots',
  sp_stat_items: 'Items',
  sp_capture: 'Log items',
  sp_add_space_ph: 'Room name, e.g. Living Room',
  sp_my_spaces: 'My Rooms',
  sp_start: 'Get started',
  sp_count_suffix: '{count}',
  sp_item_count: '{count} items',
  sp_no_positions: 'No spots yet',
  sp_first_title: "Take one photo — we'll organize it",
  sp_first_text: 'AI recognizes your items and sets up rooms and spots automatically',
  sp_first_btn: 'Take a photo',
  sp_manual_add: 'Add a room manually',
  sp_rename_space: 'Rename room',
  sp_delete_space: 'Delete room',
  sp_delete_space_msg: 'Delete "{name}" and all its spots and items?',
  web_prompt_action: '{name}\nType "delete" to delete, or a new name to rename. Leave empty to cancel:',
  web_confirm_delete: 'Delete "{name}"?',
  web_logout_confirm: 'Sign out? Your data stays in your account.',
  web_delete_account_confirm: 'Delete your account and saved data? This cannot be undone.',

  sd_no_items: 'No items yet',
  sd_items_count: '{count} items',
  sd_items_with_first: '{first} +{count} more',
  sd_meta: '{positions} spots · {items} items',
  sd_empty_title: 'No spots yet',
  sd_empty_text: 'Add a spot, or snap a photo and let AI set it up',
  sd_add_pos_ph: 'Spot name, e.g. desk, second shelf',
  sd_add_pos: 'Add spot',
  sd_shoot_room: 'Photograph this room',
  sd_rename_pos: 'Rename spot',
  sd_rename_item: 'Rename item',

  pw_page_title: 'Account',
  pw_plan_standard: 'Standard',
  pw_plan_large: 'Large Home',
  pw_plan_welcome: 'Welcome Trial',
  pw_plan_annual: 'Annual',
  pw_price_standard: '$9.99/yr',
  pw_price_large: '$17.99/yr',
  pw_desc_standard: 'One-year membership for most homes. Keep logging items with photos or videos, and find them by asking.',
  pw_desc_large: 'One-year membership for bigger homes with more rooms and belongings. Includes a higher recognition allowance.',
  pw_cta: 'Subscribe',
  pw_current_plan: 'Current plan',
  pw_plan_free: 'Free',
  pw_plan_expired: 'Membership expired',
  pw_expires: 'Expires {date}',
  pw_one_year_later: 'in one year',
  pw_expired_on: 'Expired on {date}',
  pw_expired_generic: 'Your membership has ended',
  pw_meta_free: 'v{version} · Annual plans available',
  pw_collapse: 'Hide plans',
  pw_upgrade: 'Upgrade',
  pw_subscribe: 'Go Premium',
  pw_restore: 'Restore purchases',
  pw_badge_recommend: 'Popular',
  pw_auto_renew: 'Auto-renews; cancel anytime in your Apple ID subscriptions.',
  pw_privacy: 'Privacy Policy',
  pw_terms: 'Terms of Service',
  pw_store_unavailable: 'Store products are temporarily unavailable',
  pw_store_not_ready: "Store products aren't ready yet",
  pw_store_query_failed: "Couldn't load store products",
  pw_store_connect_timeout: 'Timed out connecting to the App Store',
  pw_store_read_timeout: 'Timed out loading App Store products',
  pw_iap_missing: "This build doesn't include in-app purchases",
  pw_purchase_pending_title: 'Purchase pending approval',
  pw_purchase_pending_msg: 'The App Store received your request; it will activate once approved.',
  pw_purchase_failed: 'Purchase failed',
  pw_purchase_failed_msg: "The App Store couldn't complete the purchase. Please try again later.",
  pw_receipt_missing_title: 'Missing purchase receipt',
  pw_receipt_missing_msg: 'The App Store didn\'t return a receipt. Tap "Restore purchases" to retry.',
  pw_restored: 'Purchase restored',
  pw_activated: "You're all set",
  pw_valid_until: 'Membership active until {date}',
  pw_activated_msg: 'Your one-year membership is active',
  pw_verify_failed: 'Verification failed',
  pw_purchase_unconfirmed_title: 'Purchase not confirmed yet',
  pw_purchase_unconfirmed_msg: 'Payment completed, but the receipt hasn\'t synced yet. Tap "Restore purchases" to refresh.',
  pw_product_not_ready_title: 'Product not ready',
  pw_product_not_ready_msg: "The App Store didn't return {id}. Please try again later.",
  pw_product_loading_title: 'Products still loading',
  pw_processing: 'Processing',
  pw_wait: 'Please wait',
  pw_retry_later: 'Try later',
  pw_dev_no_restore: 'No restore needed in dev mode',
  pw_nothing_restore: 'Nothing to restore',
  pw_restore_failed: 'Restore failed',

  bf_section: 'Welcome perks',
  bf_section_meta: 'Claim your trial and invite rewards here',
  bf_claimed_title: 'Welcome trial claimed',
  bf_claim_title: 'Claim your welcome trial',
  bf_claimed_meta: 'Your membership is active',
  bf_claim_meta: 'Get a {days}-day welcome membership',
  bf_claimed: 'Claimed',
  bf_claiming: 'Claiming…',
  bf_claim: 'Claim',
  bf_my_code: 'My invite code',
  bf_redeemed_title: 'Invite code redeemed',
  bf_enter_code: 'Enter invite code',
  bf_redeemed_meta: 'One redemption per account',
  bf_redeem_meta: 'You both get a bonus when redeemed',
  bf_redeemed_ph: 'Redeemed',
  bf_code_ph: 'Enter code',
  bf_redeemed_short: 'Done',
  bf_redeeming: 'Redeeming…',
  bf_redeem: 'Redeem',
  bf_already_claimed: "You've already claimed the welcome trial",
  bf_claim_ok: '{days}-day welcome membership claimed',
  bf_claim_failed: 'Claim failed',
  bf_redeem_ok: 'Redeemed! Your bonus has been added',
  bf_redeem_failed: 'Redeem failed',
  bf_code_copied: 'Invite code copied',
  bf_share_text: 'My FindIt invite code: {code}. Enter it and we both get a bonus.',

  ac_section: 'Account & data',
  ac_section_meta: 'Sign out, or delete your account and saved data.',
  ac_logout: 'Sign out',
  ac_delete: 'Delete account',
  ac_logout_failed: 'Sign-out failed',
  ac_logout_msg: "You'll need to sign in again to see your records. Nothing gets deleted.",
  ac_delete_title: 'Delete account & data',
  ac_delete_msg: 'This removes your account, photos/videos, rooms, spots, items and chats. This cannot be undone.',
  ac_confirm_delete: 'Delete',

  wb_nav: 'Welcome perks',
  wb_title: 'Claim your welcome trial',
  wb_sub: 'Start with a free membership, then enter an invite code for a bonus.',
  wb_claimed_meta: 'Your membership is active.',
  wb_gift: 'A {days}-day membership, on us',
  wb_redeemed_meta: 'One redemption per account.',
  wb_done: 'Start using FindIt',

  og_title: 'Snap a photo to get started',
  og_text: "Open a drawer or cabinet and take a photo. AI recognizes what's inside and remembers where it is — later, just ask.",
  og_try: 'Try it now',
  og_later: 'Maybe later',

  empty_default: 'Nothing here yet',

  // 后端错误码 → 英文文案（zh 直接显示后端返回的中文 error）
  err_INSUFFICIENT_CREDITS: "You've used up your free credits. Subscribe to keep going.",
  err_DAILY_LIMIT_REACHED: "You've hit today's limit. Come back tomorrow — members get a higher limit.",
  err_EMPTY_NAME: 'Name cannot be empty',
  err_EMPTY_QUERY: 'Please enter something',
  err_QUERY_TOO_LONG: 'Message too long — keep it under 500 characters',
  err_NOT_FOUND: 'Not found',
  err_AUTH_FAILED: 'Session expired. Please sign in again.',
  err_SUBSCRIPTION_EXPIRED: 'Your subscription has expired. Please renew.',
  err_IAP_VERIFICATION_FAILED: 'Purchase verification failed',
  err_INVALID_REQUEST: 'Invalid request',
  err_FILE_REQUIRED: 'Please attach a photo or video',
  err_UNSUPPORTED_FILE_TYPE: 'Unsupported file type',
  err_FILE_TOO_LARGE: 'File too large (max 50MB)',
  err_VIDEO_PROCESSING_FAILED: "Couldn't process the video",
  err_EMPTY_INVITE_CODE: 'Please enter an invite code',
  err_INVITE_ALREADY_REDEEMED: "You've already redeemed an invite code",
  err_INVITE_OWN_CODE: "You can't use your own invite code",
  err_INVITE_CODE_NOT_FOUND: 'Invite code not found',
  err_ITEM_NOT_FOUND: 'Item not found',
  err_INTERNAL_ERROR: 'Something went wrong. Please try again later.'
};

const dicts = { zh, en };

export const isZh = lang === 'zh';

export function t(key, params) {
  let str = dicts[lang][key] ?? zh[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      str = str.split(`{${k}}`).join(String(v));
    }
  }
  return str;
}

// 后端错误 → 展示文案：中文用户优先显示后端中文 error（更具体），
// 英文用户优先按 code 查字典，查不到 fallback 到 error 原文
export function apiErrorMessage(err) {
  const code = err?.code;
  const mapped = code && en[`err_${code}`] ? t(`err_${code}`) : null;
  if (isZh) return err?.message || mapped || t('err_INTERNAL_ERROR');
  return mapped || err?.message || t('err_INTERNAL_ERROR');
}

export function formatDate(value) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  if (isZh) return `${date.getFullYear()}年${date.getMonth() + 1}月${date.getDate()}日`;
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}
